import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'AutoCSR Terms of Service — the legal agreement governing your use of the AutoCSR AI customer service automation platform.',
  alternates: { canonical: '/terms' },
  openGraph: {
    title: 'Terms of Service | AutoCSR',
    description: 'Legal terms governing use of the AutoCSR platform.',
  },
}

const EFFECTIVE_DATE = 'June 8, 2026'
const COMPANY = 'TechSci, Inc.'
const COMPANY_STATE = 'Delaware'
const EMAIL_LEGAL = 'legal@techsci.co'
const EMAIL_SUPPORT = 'support@autocsr.ai'

export default function TermsPage() {
  return (
    <div style={{ background: '#090910', minHeight: '100vh' }}>
      {/* Nav */}
      <nav
        className="sticky top-0 z-50 flex items-center justify-between px-6 py-4 border-b"
        style={{ background: 'rgba(9,9,16,0.92)', borderColor: 'rgba(255,255,255,0.06)', backdropFilter: 'blur(8px)' }}
      >
        <Link href="/" className="font-display font-bold text-[15px]" style={{ color: '#e8e8f0', letterSpacing: '-0.02em' }}>
          AUTOCSR
        </Link>
        <Link href="/" className="text-[13px] transition-colors" style={{ color: '#606075' }}>
          ← Back to home
        </Link>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16">
        {/* Header */}
        <div className="mb-12">
          <p className="font-mono text-[10px] tracking-widest uppercase mb-4" style={{ color: '#4f46e5' }}>
            Legal
          </p>
          <h1 className="font-display font-bold mb-3" style={{ fontSize: 'clamp(28px, 4vw, 40px)', color: '#e8e8f0', letterSpacing: '-0.03em' }}>
            Terms of Service
          </h1>
          <p className="font-mono text-[12px]" style={{ color: '#606075' }}>
            Effective date: {EFFECTIVE_DATE} · {COMPANY} · {COMPANY_STATE}
          </p>
        </div>

        <LegalBody>
          <p>
            These Terms of Service (&quot;Agreement&quot;) govern your access to and use of the AutoCSR platform, APIs,
            and related services (collectively, the &quot;Service&quot;) provided by <strong>{COMPANY}</strong>,
            a corporation registered in {COMPANY_STATE}, United States (&quot;Company,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;).
          </p>
          <p>
            By creating an account, accessing the Service, or executing an Order Form referencing this Agreement,
            you (&quot;Customer,&quot; &quot;Operator,&quot; or &quot;you&quot;) agree to be bound by this Agreement. If you are
            accepting on behalf of a company or legal entity, you represent that you have authority to bind that
            entity to this Agreement.
          </p>
          <p>
            <strong>If you do not agree to these terms, do not access or use the Service.</strong>
          </p>

          <Section n="1" title="Definitions">
            <dl>
              <dt>&quot;Service&quot;</dt>
              <dd>The AutoCSR AI-powered customer service automation platform, including all APIs, dashboards,
              inference infrastructure, training pipelines, and related software made available by Company.</dd>

              <dt>&quot;Customer Data&quot;</dt>
              <dd>All data, content, and information that Customer or its end users submit to the Service,
              including but not limited to customer service queries, conversation transcripts, knowledge base
              documents, and configuration settings.</dd>

              <dt>&quot;AI Output&quot;</dt>
              <dd>Text, classifications, scores, and other content generated by the Service in response to
              Customer Data inputs.</dd>

              <dt>&quot;Authorized User&quot;</dt>
              <dd>An individual employee or contractor of Customer who is permitted to access the Service
              under Customer&apos;s account.</dd>

              <dt>&quot;Subscription&quot;</dt>
              <dd>Customer&apos;s paid or free tier plan providing access to specified Service features and
              query volume limits as described on the Pricing page.</dd>

              <dt>&quot;Order Form&quot;</dt>
              <dd>Any written or electronic order, including checkout flows, that specifies Subscription
              tier, fees, and any additional terms agreed between the parties.</dd>
            </dl>
          </Section>

          <Section n="2" title="Service Access and Accounts">
            <p>
              <strong>2.1 Account Registration.</strong> You must create an account to access the Service.
              You agree to provide accurate, current, and complete information and to keep it updated. You
              are responsible for all activity that occurs under your account.
            </p>
            <p>
              <strong>2.2 Account Security.</strong> You are responsible for maintaining the confidentiality
              of your API keys and login credentials. Notify us immediately at <a href={`mailto:${EMAIL_SUPPORT}`}>{EMAIL_SUPPORT}</a> if
              you believe your account has been compromised.
            </p>
            <p>
              <strong>2.3 Authorized Users.</strong> You may permit Authorized Users to access the Service
              on your behalf. You are responsible for ensuring Authorized Users comply with this Agreement.
            </p>
            <p>
              <strong>2.4 Acceptable Use.</strong> You may use the Service only for lawful purposes and
              in accordance with this Agreement. You agree not to: (a) reverse engineer, decompile, or
              disassemble the Service; (b) use the Service to train competing AI models without our written
              consent; (c) submit queries containing personal data in violation of applicable privacy laws;
              (d) attempt to circumvent rate limits, security controls, or access restrictions; (e) resell
              or sublicense the Service to third parties without written authorization.
            </p>
          </Section>

          <Section n="3" title="Subscriptions, Fees, and Payment">
            <p>
              <strong>3.1 Subscription Tiers.</strong> The Service is offered on tiered subscription plans
              (Free, Starter, Growth, Enterprise) as described on our Pricing page. Features and query
              volume limits vary by tier.
            </p>
            <p>
              <strong>3.2 Fees.</strong> Paid Subscriptions are billed in advance on a monthly or annual
              basis as specified in your Order Form. All fees are in US Dollars (USD) and are non-refundable
              except as expressly set out in our Refund Policy or as required by applicable law.
            </p>
            <p>
              <strong>3.3 Payment Processing.</strong> Payments are processed by our third-party payment
              provider (currently Polar / Stripe). By providing payment information, you authorize us to
              charge the applicable fees. You are responsible for all taxes, levies, or duties applicable
              to your purchase, excluding taxes on Company&apos;s net income.
            </p>
            <p>
              <strong>3.4 Auto-Renewal.</strong> Subscriptions automatically renew at the end of each
              billing period unless cancelled before the renewal date. You may cancel at any time through
              your account settings.
            </p>
            <p>
              <strong>3.5 Overages.</strong> If your usage exceeds the query limits of your Subscription
              tier, we reserve the right to throttle Service access or charge overage fees as described
              in the applicable Order Form or Pricing page.
            </p>
            <p>
              <strong>3.6 Pilot Programs.</strong> Free pilot periods (including any agreed pilot for
              OKBET or similar operators) are subject to separate written pilot agreements. Pilot access
              does not create any obligation by Company to continue providing the Service at no charge
              after the pilot period ends.
            </p>
            <p>
              <strong>3.7 Price Changes.</strong> Company may change fees upon 30 days&apos; written notice.
              Price changes take effect at the next renewal date.
            </p>
          </Section>

          <Section n="4" title="Intellectual Property">
            <p>
              <strong>4.1 Company IP.</strong> Company retains all right, title, and interest in and to
              the Service, including all underlying technology, AI models, LoRA adapters, training
              methodologies, and software. Nothing in this Agreement transfers any IP rights to Customer.
            </p>
            <p>
              <strong>4.2 Customer Data Ownership.</strong> Customer retains all right, title, and interest
              in Customer Data. You grant Company a limited, non-exclusive, worldwide license to process
              Customer Data solely to provide and improve the Service.
            </p>
            <p>
              <strong>4.3 AI Output.</strong> Subject to payment of applicable fees and compliance with
              this Agreement, Company assigns to Customer all right, title, and interest in AI Output
              generated from Customer&apos;s specific data inputs. Company retains the right to use aggregated,
              anonymized, and de-identified data to improve the Service.
            </p>
            <p>
              <strong>4.4 Feedback.</strong> If you provide feedback, suggestions, or improvements
              regarding the Service, Company may use such feedback without restriction or compensation.
            </p>
          </Section>

          <Section n="5" title="Data Processing and Privacy">
            <p>
              <strong>5.1 Privacy Policy.</strong> Company&apos;s collection and use of personal information
              is described in the <Link href="/privacy">Privacy Policy</Link>, incorporated herein by reference.
            </p>
            <p>
              <strong>5.2 Customer Responsibility for Personal Data.</strong> You are responsible for
              ensuring you have lawful basis to submit any personal data to the Service, including obtaining
              necessary consents from your end users. You must configure the Service to minimize submission
              of personally identifiable information where possible.
            </p>
            <p>
              <strong>5.3 Data Processing Agreement.</strong> Enterprise customers requiring a Data Processing
              Agreement (DPA) for GDPR or equivalent compliance may request one at{' '}
              <a href={`mailto:${EMAIL_LEGAL}`}>{EMAIL_LEGAL}</a>.
            </p>
            <p>
              <strong>5.4 Security.</strong> Company implements industry-standard technical and organizational
              security measures including encryption in transit (TLS 1.3), encryption at rest, access controls,
              and regular security reviews. However, no system is perfectly secure, and Company cannot
              guarantee absolute security of Customer Data.
            </p>
          </Section>

          <Section n="6" title="Confidentiality">
            <p>
              Each party agrees to keep confidential any non-public information disclosed by the other
              party that is designated as confidential or that reasonably should be understood to be
              confidential (&quot;Confidential Information&quot;). Each party will use the other&apos;s Confidential
              Information only to perform its obligations under this Agreement and will not disclose it
              to third parties without the disclosing party&apos;s prior written consent, except as required
              by law. This obligation survives termination of this Agreement for three (3) years.
            </p>
          </Section>

          <Section n="7" title="Warranties and Disclaimers">
            <p>
              <strong>7.1 Company Warranty.</strong> Company warrants that the Service will perform
              materially in accordance with applicable documentation during the Subscription term. This
              warranty does not apply to defects caused by Customer&apos;s misuse, modification, or breach
              of this Agreement.
            </p>
            <p>
              <strong>7.2 Disclaimer of Warranties.</strong> EXCEPT AS EXPRESSLY SET OUT IN SECTION 7.1,
              THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE.&quot; COMPANY EXPRESSLY DISCLAIMS ALL
              WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
              PARTICULAR PURPOSE, AND NON-INFRINGEMENT. COMPANY DOES NOT WARRANT THAT THE SERVICE WILL
              BE UNINTERRUPTED, ERROR-FREE, OR THAT AI OUTPUT WILL BE ACCURATE OR COMPLETE.
            </p>
            <p>
              <strong>7.3 AI Output Disclaimer.</strong> AI Output is generated by machine learning models
              and may contain errors, inaccuracies, or hallucinations. Customer is solely responsible
              for reviewing AI Output before use in production customer-facing workflows. AutoCSR provides
              human review queues and audit scoring to assist in this process but does not guarantee the
              accuracy of any AI Output.
            </p>
            <p>
              <strong>7.4 Regulated Industry.</strong> The Service is a general-purpose AI automation
              tool. Company makes no warranties regarding compliance with gaming regulations, AML/KYC
              requirements, or other iGaming-specific regulatory obligations. Customer is solely
              responsible for ensuring its use of the Service complies with all applicable laws and
              regulations in its jurisdiction.
            </p>
          </Section>

          <Section n="8" title="Limitation of Liability">
            <p>
              <strong>8.1 Exclusion of Consequential Damages.</strong> NEITHER PARTY WILL BE LIABLE
              FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES,
              OR DAMAGES FOR LOSS OF PROFITS, REVENUE, GOODWILL, DATA, OR BUSINESS INTERRUPTION,
              ARISING OUT OF OR RELATED TO THIS AGREEMENT, EVEN IF ADVISED OF THE POSSIBILITY OF
              SUCH DAMAGES.
            </p>
            <p>
              <strong>8.2 Cap on Liability.</strong> COMPANY&apos;S TOTAL CUMULATIVE LIABILITY ARISING OUT
              OF OR RELATED TO THIS AGREEMENT WILL NOT EXCEED THE GREATER OF (A) THE TOTAL FEES PAID
              BY CUSTOMER IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM OR (B) USD $500.
            </p>
            <p>
              <strong>8.3 Essential Basis.</strong> THE LIMITATIONS IN THIS SECTION 8 REFLECT THE
              ALLOCATION OF RISK BETWEEN THE PARTIES AND ARE AN ESSENTIAL ELEMENT OF THE BASIS OF
              THE BARGAIN BETWEEN THE PARTIES. COMPANY WOULD NOT ENTER INTO THIS AGREEMENT WITHOUT
              THESE LIMITATIONS.
            </p>
          </Section>

          <Section n="9" title="Indemnification">
            <p>
              Customer will indemnify, defend, and hold harmless Company and its officers, directors,
              employees, and agents from any claim, demand, loss, or damages, including reasonable legal
              fees, arising out of: (a) Customer Data; (b) Customer&apos;s use of the Service in violation
              of this Agreement; (c) Customer&apos;s violation of any applicable law or third-party right;
              or (d) Customer&apos;s end users&apos; use of any product or service powered by the Service.
            </p>
          </Section>

          <Section n="10" title="Term and Termination">
            <p>
              <strong>10.1 Term.</strong> This Agreement commences on the date you create an account
              and continues until terminated.
            </p>
            <p>
              <strong>10.2 Termination by Customer.</strong> You may terminate your Subscription at
              any time by cancelling through your account settings. Termination takes effect at the
              end of the current billing period.
            </p>
            <p>
              <strong>10.3 Termination by Company.</strong> Company may suspend or terminate access
              immediately if: (a) you breach this Agreement and fail to cure within 10 days of notice;
              (b) you are in material breach of payment obligations; or (c) Company determines in its
              reasonable discretion that continued access poses a security, legal, or reputational risk.
            </p>
            <p>
              <strong>10.4 Effect of Termination.</strong> Upon termination, all rights granted under
              this Agreement cease. Customer may export Customer Data for 30 days after termination.
              After this period, Company may permanently delete Customer Data. Sections 4, 6, 7, 8, 9,
              11, and 12 survive termination.
            </p>
          </Section>

          <Section n="11" title="Governing Law and Disputes">
            <p>
              This Agreement is governed by the laws of the State of Delaware, United States, without
              regard to conflict of law principles. Any dispute arising under or related to this Agreement
              that cannot be resolved informally within 30 days will be resolved by binding arbitration
              administered by JAMS under its Commercial Arbitration Rules, with proceedings conducted
              in English in Wilmington, Delaware. The United Nations Convention on Contracts for the
              International Sale of Goods does not apply.
            </p>
            <p>
              <strong>Class Action Waiver:</strong> You agree that any claim will be brought in an
              individual capacity only, and not as a plaintiff or class member in any purported class
              or representative proceeding.
            </p>
          </Section>

          <Section n="12" title="General Provisions">
            <p>
              <strong>12.1 Entire Agreement.</strong> This Agreement, together with any Order Forms,
              the Privacy Policy, and the Refund Policy, constitutes the entire agreement between the
              parties and supersedes all prior agreements relating to its subject matter.
            </p>
            <p>
              <strong>12.2 Amendments.</strong> Company may modify this Agreement by posting an updated
              version and providing 30 days&apos; notice by email. Your continued use after the effective
              date constitutes acceptance of the modified terms.
            </p>
            <p>
              <strong>12.3 Severability.</strong> If any provision is found unenforceable, the remaining
              provisions remain in full force.
            </p>
            <p>
              <strong>12.4 Waiver.</strong> Failure to enforce any provision is not a waiver of the
              right to enforce it in the future.
            </p>
            <p>
              <strong>12.5 Assignment.</strong> Customer may not assign this Agreement without Company&apos;s
              prior written consent. Company may assign this Agreement in connection with a merger,
              acquisition, or sale of assets.
            </p>
            <p>
              <strong>12.6 Force Majeure.</strong> Neither party is liable for delays or failures caused
              by circumstances beyond its reasonable control, including natural disasters, government
              actions, infrastructure failures, or pandemic-related disruptions.
            </p>
          </Section>

          <Section n="13" title="Contact">
            <p>
              For legal inquiries: <a href={`mailto:${EMAIL_LEGAL}`}>{EMAIL_LEGAL}</a><br />
              For general support: <a href={`mailto:${EMAIL_SUPPORT}`}>{EMAIL_SUPPORT}</a><br />
              {COMPANY} · 1209 Orange Street · Wilmington, DE 19801 · United States
            </p>
          </Section>
        </LegalBody>

        {/* Footer nav */}
        <div className="mt-16 pt-8 border-t flex flex-wrap gap-6" style={{ borderColor: 'rgba(255,255,255,0.06)' }}>
          {[
            { href: '/privacy', label: 'Privacy Policy' },
            { href: '/refund', label: 'Refund Policy' },
            { href: '/', label: 'Back to AutoCSR' },
          ].map(link => (
            <Link key={link.href} href={link.href} className="font-mono text-[11px] transition-colors"
              style={{ color: '#606075' }}>
              {link.label}
            </Link>
          ))}
        </div>
      </div>
    </div>
  )
}

function LegalBody({ children }: { children: React.ReactNode }) {
  return (
    <div
      className="space-y-6 text-[14px] leading-relaxed legal-body"
      style={{ color: '#9898b0' }}
    >
      <style>{`
        .legal-body p { margin-bottom: 0.75rem; }
        .legal-body a { color: #a5a0ff; text-decoration: underline; text-decoration-color: rgba(165,160,255,0.3); }
        .legal-body a:hover { color: #e8e8f0; }
        .legal-body strong { color: #e8e8f0; font-weight: 600; }
        .legal-body dl dt { color: #e8e8f0; font-weight: 600; margin-top: 0.75rem; font-size: 13px; font-family: var(--font-mono); }
        .legal-body dl dd { margin-left: 1.25rem; margin-bottom: 0.5rem; font-size: 13px; }
        .legal-body h3 { color: #e8e8f0; }
      `}</style>
      {children}
    </div>
  )
}

function Section({ n, title, children }: { n: string; title: string; children: React.ReactNode }) {
  return (
    <div className="space-y-3">
      <h2
        className="font-display font-bold"
        style={{ fontSize: 16, color: '#e8e8f0', letterSpacing: '-0.01em' }}
        id={`section-${n}`}
      >
        {n}. {title}
      </h2>
      {children}
    </div>
  )
}
